### PR TITLE
Fixes that should make the benchmark work

### PR DESCRIPTION
**Pull request by Jean-Eudes-le-retour**
Here are the modifications I did:

- I added opencv in the webots container as it is the one used on the simulation server, which will run the default controller locally so it need its dependencies (I should explain it better in the instructions)
- the supervisor must print the score in the "performance:SCORE" format to tell the automated script that the benchmark finished correctly
- it's better if the robot is set as not synchronized in the world file just in case the participant's controller never calls robot.step() and would stall evaluation (I didn't find any elegant solution to remedy this, I should think about it more)
- I use a regex to fetch the link in the README badge to get the link to the leaderboard and I didn't expect it to be multiline which is a correct markdown syntax. I'll see if I can fix the regex

\+ I added the other regex fix to ignore .git if it is at the end of the registration link
\+ removed the robotbenchmark functions

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
Thank you!

> I added opencv in the webots container as it is the one used on the simulation server, which will run the default controller locally so it need its dependencies (I should explain it better in the instructions)

Does this mean that if a user wants for example to use tensorflow python module in its controller, the organizer needs to add tensorflow library in the Webots Dockerfile of the benchmark?

**Comment by Jean-Eudes-le-retour** [comment]
> Does this mean that if a user wants for example to use tensorflow python module in its controller, the organizer needs to add tensorflow library in the Webots Dockerfile of the benchmark?

No, but that bring up something I am not really sure how to handle: Currently there are two dockerfiles, one for the webots simulation and one for the competitor controller. The thing is that the Webots container is currently used in the evaluation CI and on the simulation server for the online testing.

Technically is would be better to have three dockerfiles:
- one for the online testing where Webots launches the default controller locally to get the stdout of the controller, so it would need the dependencies for Webots and the default controller
- two dockerfiles for the GitHub CI testing where Webots and the controllers have their separate containers and their separate dependencies.

But we do this, the organizer would need to manage three different dockers which isn't practical, but would be more logical. 

What do you think would be the best way to handle this?

**Comment by stefaniapedrazzi** [comment]
What do you mean by "default controller" launched by Webots?
The benchmark supervisor?

There are already three Dockerfiles:
* 2 in the organizer repo (this):
  * `Dockerfile` for the dependencies of Webots, supervisor controllers etc.
  * `controller_Dockerfile` for the dependencies of the default controller
* 1 in the user repo:
  * `controller_Dockerfile` for the dependencies of the user controller

**Comment by Jean-Eudes-le-retour** [comment]
> What do you mean by "default controller" launched by Webots?

The example controller provided in the organizer repository for the participants

Currently the Docker container separation between webots and the robot controller is only done in the GitHub CI and not on the webots.cloud simulation server as it would need some changes to make it work. But I haven't looked into it, I'll have a look to see if it is that difficult

**Pull request merged**
